title: Hello!
email: dharmanshu39@gmail.com
linkedin_url: https://www.linkedin.com/in/dharmanshu-saini
baseurl: "" 
url: "http://dsaini.dev"
github_username:  dharmanshu24

remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed

theme_config:
  appearance: "light"
  back_home_text: ".."
  date_format: "%Y-%m-%d" 
  show_description: false 
  lowercase_titles: true 

sass:
  style: compressed